//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BluLogisticsService.co.com.tcc.clientes.liquidacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LiquidacionAcuerdosSoap", Namespace="http://clientes.tcc.com.co/")]
    public partial class LiquidacionAcuerdos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LiquidaDespachoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LiquidaDespacho2OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarMaestroCiudadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarliquidacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback HabilitarCotizacionAcuerdosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LiquidacionAcuerdos() {
            this.Url = global::BluLogisticsService.Properties.Settings.Default.TCCService_co_com_tcc_clientes_liquidacion_LiquidacionAcuerdos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LiquidaDespachoCompletedEventHandler LiquidaDespachoCompleted;
        
        /// <remarks/>
        public event LiquidaDespacho2CompletedEventHandler LiquidaDespacho2Completed;
        
        /// <remarks/>
        public event consultarMaestroCiudadesCompletedEventHandler consultarMaestroCiudadesCompleted;
        
        /// <remarks/>
        public event consultarliquidacionCompletedEventHandler consultarliquidacionCompleted;
        
        /// <remarks/>
        public event HabilitarCotizacionAcuerdosCompletedEventHandler HabilitarCotizacionAcuerdosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clientes.tcc.com.co/LiquidaDespacho", RequestNamespace="http://clientes.tcc.com.co/", ResponseNamespace="http://clientes.tcc.com.co/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LiquidaDespacho(string Clave, string Despacho, ref string Liquidacion, ref int Respuesta, ref string Mensaje) {
            object[] results = this.Invoke("LiquidaDespacho", new object[] {
                        Clave,
                        Despacho,
                        Liquidacion,
                        Respuesta,
                        Mensaje});
            Liquidacion = ((string)(results[0]));
            Respuesta = ((int)(results[1]));
            Mensaje = ((string)(results[2]));
        }
        
        /// <remarks/>
        public void LiquidaDespachoAsync(string Clave, string Despacho, string Liquidacion, int Respuesta, string Mensaje) {
            this.LiquidaDespachoAsync(Clave, Despacho, Liquidacion, Respuesta, Mensaje, null);
        }
        
        /// <remarks/>
        public void LiquidaDespachoAsync(string Clave, string Despacho, string Liquidacion, int Respuesta, string Mensaje, object userState) {
            if ((this.LiquidaDespachoOperationCompleted == null)) {
                this.LiquidaDespachoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLiquidaDespachoOperationCompleted);
            }
            this.InvokeAsync("LiquidaDespacho", new object[] {
                        Clave,
                        Despacho,
                        Liquidacion,
                        Respuesta,
                        Mensaje}, this.LiquidaDespachoOperationCompleted, userState);
        }
        
        private void OnLiquidaDespachoOperationCompleted(object arg) {
            if ((this.LiquidaDespachoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LiquidaDespachoCompleted(this, new LiquidaDespachoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clientes.tcc.com.co/LiquidaDespacho2", RequestNamespace="http://clientes.tcc.com.co/", ResponseNamespace="http://clientes.tcc.com.co/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LiquidaDespacho2(string Clave, Liquidacion2 Despacho, ref string Liquidacion, ref int Respuesta, ref string Mensaje) {
            object[] results = this.Invoke("LiquidaDespacho2", new object[] {
                        Clave,
                        Despacho,
                        Liquidacion,
                        Respuesta,
                        Mensaje});
            Liquidacion = ((string)(results[0]));
            Respuesta = ((int)(results[1]));
            Mensaje = ((string)(results[2]));
        }
        
        /// <remarks/>
        public void LiquidaDespacho2Async(string Clave, Liquidacion2 Despacho, string Liquidacion, int Respuesta, string Mensaje) {
            this.LiquidaDespacho2Async(Clave, Despacho, Liquidacion, Respuesta, Mensaje, null);
        }
        
        /// <remarks/>
        public void LiquidaDespacho2Async(string Clave, Liquidacion2 Despacho, string Liquidacion, int Respuesta, string Mensaje, object userState) {
            if ((this.LiquidaDespacho2OperationCompleted == null)) {
                this.LiquidaDespacho2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLiquidaDespacho2OperationCompleted);
            }
            this.InvokeAsync("LiquidaDespacho2", new object[] {
                        Clave,
                        Despacho,
                        Liquidacion,
                        Respuesta,
                        Mensaje}, this.LiquidaDespacho2OperationCompleted, userState);
        }
        
        private void OnLiquidaDespacho2OperationCompleted(object arg) {
            if ((this.LiquidaDespacho2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LiquidaDespacho2Completed(this, new LiquidaDespacho2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clientes.tcc.com.co/consultarMaestroCiudades", RequestNamespace="http://clientes.tcc.com.co/", ResponseNamespace="http://clientes.tcc.com.co/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ciudadesRespuesta consultarMaestroCiudades(string Clave) {
            object[] results = this.Invoke("consultarMaestroCiudades", new object[] {
                        Clave});
            return ((ciudadesRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void consultarMaestroCiudadesAsync(string Clave) {
            this.consultarMaestroCiudadesAsync(Clave, null);
        }
        
        /// <remarks/>
        public void consultarMaestroCiudadesAsync(string Clave, object userState) {
            if ((this.consultarMaestroCiudadesOperationCompleted == null)) {
                this.consultarMaestroCiudadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarMaestroCiudadesOperationCompleted);
            }
            this.InvokeAsync("consultarMaestroCiudades", new object[] {
                        Clave}, this.consultarMaestroCiudadesOperationCompleted, userState);
        }
        
        private void OnconsultarMaestroCiudadesOperationCompleted(object arg) {
            if ((this.consultarMaestroCiudadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarMaestroCiudadesCompleted(this, new consultarMaestroCiudadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clientes.tcc.com.co/consultarliquidacion", RequestNamespace="http://clientes.tcc.com.co/", ResponseNamespace="http://clientes.tcc.com.co/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LiquidacionRespuesta consultarliquidacion(string Clave, Liquidacion Liquidacion) {
            object[] results = this.Invoke("consultarliquidacion", new object[] {
                        Clave,
                        Liquidacion});
            return ((LiquidacionRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void consultarliquidacionAsync(string Clave, Liquidacion Liquidacion) {
            this.consultarliquidacionAsync(Clave, Liquidacion, null);
        }
        
        /// <remarks/>
        public void consultarliquidacionAsync(string Clave, Liquidacion Liquidacion, object userState) {
            if ((this.consultarliquidacionOperationCompleted == null)) {
                this.consultarliquidacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarliquidacionOperationCompleted);
            }
            this.InvokeAsync("consultarliquidacion", new object[] {
                        Clave,
                        Liquidacion}, this.consultarliquidacionOperationCompleted, userState);
        }
        
        private void OnconsultarliquidacionOperationCompleted(object arg) {
            if ((this.consultarliquidacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarliquidacionCompleted(this, new consultarliquidacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clientes.tcc.com.co/HabilitarCotizacionAcuerdos", RequestNamespace="http://clientes.tcc.com.co/", ResponseNamespace="http://clientes.tcc.com.co/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HabilitarCotizacionAcuerdos(string clave, string usuario, ref clsOpcion[] Opciones, ref clsCuenta[] Cuentas, ref int Respuesta, ref string Mensaje) {
            object[] results = this.Invoke("HabilitarCotizacionAcuerdos", new object[] {
                        clave,
                        usuario,
                        Opciones,
                        Cuentas,
                        Respuesta,
                        Mensaje});
            Opciones = ((clsOpcion[])(results[1]));
            Cuentas = ((clsCuenta[])(results[2]));
            Respuesta = ((int)(results[3]));
            Mensaje = ((string)(results[4]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HabilitarCotizacionAcuerdosAsync(string clave, string usuario, clsOpcion[] Opciones, clsCuenta[] Cuentas, int Respuesta, string Mensaje) {
            this.HabilitarCotizacionAcuerdosAsync(clave, usuario, Opciones, Cuentas, Respuesta, Mensaje, null);
        }
        
        /// <remarks/>
        public void HabilitarCotizacionAcuerdosAsync(string clave, string usuario, clsOpcion[] Opciones, clsCuenta[] Cuentas, int Respuesta, string Mensaje, object userState) {
            if ((this.HabilitarCotizacionAcuerdosOperationCompleted == null)) {
                this.HabilitarCotizacionAcuerdosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHabilitarCotizacionAcuerdosOperationCompleted);
            }
            this.InvokeAsync("HabilitarCotizacionAcuerdos", new object[] {
                        clave,
                        usuario,
                        Opciones,
                        Cuentas,
                        Respuesta,
                        Mensaje}, this.HabilitarCotizacionAcuerdosOperationCompleted, userState);
        }
        
        private void OnHabilitarCotizacionAcuerdosOperationCompleted(object arg) {
            if ((this.HabilitarCotizacionAcuerdosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HabilitarCotizacionAcuerdosCompleted(this, new HabilitarCotizacionAcuerdosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Liquidacion2 {
        
        private string cuentaField;
        
        private string idciudadorigenField;
        
        private string idciudaddestinoField;
        
        private string valormercanciaField;
        
        private string recogidaField;
        
        private string traecdField;
        
        private string recogecdField;
        
        private string boomerangField;
        
        private unidad2[] unidadesField;
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string idciudadorigen {
            get {
                return this.idciudadorigenField;
            }
            set {
                this.idciudadorigenField = value;
            }
        }
        
        /// <remarks/>
        public string idciudaddestino {
            get {
                return this.idciudaddestinoField;
            }
            set {
                this.idciudaddestinoField = value;
            }
        }
        
        /// <remarks/>
        public string valormercancia {
            get {
                return this.valormercanciaField;
            }
            set {
                this.valormercanciaField = value;
            }
        }
        
        /// <remarks/>
        public string recogida {
            get {
                return this.recogidaField;
            }
            set {
                this.recogidaField = value;
            }
        }
        
        /// <remarks/>
        public string traecd {
            get {
                return this.traecdField;
            }
            set {
                this.traecdField = value;
            }
        }
        
        /// <remarks/>
        public string recogecd {
            get {
                return this.recogecdField;
            }
            set {
                this.recogecdField = value;
            }
        }
        
        /// <remarks/>
        public string boomerang {
            get {
                return this.boomerangField;
            }
            set {
                this.boomerangField = value;
            }
        }
        
        /// <remarks/>
        public unidad2[] unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class unidad2 {
        
        private string tipoempaqueField;
        
        private string unidadesField;
        
        private string pesoField;
        
        private string volumenField;
        
        private string altoField;
        
        private string largoField;
        
        private string anchoField;
        
        /// <remarks/>
        public string tipoempaque {
            get {
                return this.tipoempaqueField;
            }
            set {
                this.tipoempaqueField = value;
            }
        }
        
        /// <remarks/>
        public string unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
        
        /// <remarks/>
        public string peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        public string volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        public string alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
            }
        }
        
        /// <remarks/>
        public string largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
            }
        }
        
        /// <remarks/>
        public string ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class clsCuenta {
        
        private int numeroField;
        
        private string nombreField;
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class clsOpcion {
        
        private int iDOpcionField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        private string uRLField;
        
        /// <remarks/>
        public int IDOpcion {
            get {
                return this.iDOpcionField;
            }
            set {
                this.iDOpcionField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class TipoTarifa {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class ConceptoAgrupado {
        
        private string idtipoconceptoField;
        
        private string descripcionField;
        
        private string valorField;
        
        /// <remarks/>
        public string idtipoconcepto {
            get {
                return this.idtipoconceptoField;
            }
            set {
                this.idtipoconceptoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Concepto {
        
        private string idconceptoField;
        
        private string descripcionField;
        
        private string valorField;
        
        /// <remarks/>
        public string idconcepto {
            get {
                return this.idconceptoField;
            }
            set {
                this.idconceptoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Total {
        
        private string valortarifaField;
        
        private string totalpesofacturadoField;
        
        private string totalpesorealField;
        
        private string totalpesovolumenField;
        
        private string totalunidadesField;
        
        private string totaldespachoField;
        
        private string valorboomerangField;
        
        private string valorserviciorecogidaField;
        
        /// <remarks/>
        public string valortarifa {
            get {
                return this.valortarifaField;
            }
            set {
                this.valortarifaField = value;
            }
        }
        
        /// <remarks/>
        public string totalpesofacturado {
            get {
                return this.totalpesofacturadoField;
            }
            set {
                this.totalpesofacturadoField = value;
            }
        }
        
        /// <remarks/>
        public string totalpesoreal {
            get {
                return this.totalpesorealField;
            }
            set {
                this.totalpesorealField = value;
            }
        }
        
        /// <remarks/>
        public string totalpesovolumen {
            get {
                return this.totalpesovolumenField;
            }
            set {
                this.totalpesovolumenField = value;
            }
        }
        
        /// <remarks/>
        public string totalunidades {
            get {
                return this.totalunidadesField;
            }
            set {
                this.totalunidadesField = value;
            }
        }
        
        /// <remarks/>
        public string totaldespacho {
            get {
                return this.totaldespachoField;
            }
            set {
                this.totaldespachoField = value;
            }
        }
        
        /// <remarks/>
        public string valorboomerang {
            get {
                return this.valorboomerangField;
            }
            set {
                this.valorboomerangField = value;
            }
        }
        
        /// <remarks/>
        public string valorserviciorecogida {
            get {
                return this.valorserviciorecogidaField;
            }
            set {
                this.valorserviciorecogidaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Moneda {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class LiquidacionRespuesta {
        
        private string idliquidacionField;
        
        private Moneda monedaField;
        
        private Total totalField;
        
        private Concepto[] conceptosField;
        
        private ConceptoAgrupado[] subtotalesField;
        
        private TipoTarifa tipotarifaField;
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        public string idliquidacion {
            get {
                return this.idliquidacionField;
            }
            set {
                this.idliquidacionField = value;
            }
        }
        
        /// <remarks/>
        public Moneda moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        public Total total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public Concepto[] conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        public ConceptoAgrupado[] subtotales {
            get {
                return this.subtotalesField;
            }
            set {
                this.subtotalesField = value;
            }
        }
        
        /// <remarks/>
        public TipoTarifa tipotarifa {
            get {
                return this.tipotarifaField;
            }
            set {
                this.tipotarifaField = value;
            }
        }
        
        /// <remarks/>
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Respuesta {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string codigointernoField;
        
        private string mensajeinternoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string codigointerno {
            get {
                return this.codigointernoField;
            }
            set {
                this.codigointernoField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeinterno {
            get {
                return this.mensajeinternoField;
            }
            set {
                this.mensajeinternoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class unidad {
        
        private string numerounidadesField;
        
        private string pesorealField;
        
        private string pesovolumenField;
        
        private string altoField;
        
        private string largoField;
        
        private string anchoField;
        
        private string tipoempaqueField;
        
        /// <remarks/>
        public string numerounidades {
            get {
                return this.numerounidadesField;
            }
            set {
                this.numerounidadesField = value;
            }
        }
        
        /// <remarks/>
        public string pesoreal {
            get {
                return this.pesorealField;
            }
            set {
                this.pesorealField = value;
            }
        }
        
        /// <remarks/>
        public string pesovolumen {
            get {
                return this.pesovolumenField;
            }
            set {
                this.pesovolumenField = value;
            }
        }
        
        /// <remarks/>
        public string alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
            }
        }
        
        /// <remarks/>
        public string largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
            }
        }
        
        /// <remarks/>
        public string ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoempaque {
            get {
                return this.tipoempaqueField;
            }
            set {
                this.tipoempaqueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Liquidacion {
        
        private string tipoenvioField;
        
        private string idciudadorigenField;
        
        private string idciudaddestinoField;
        
        private string valormercanciaField;
        
        private string boomerangField;
        
        private string cuentaField;
        
        private string fecharemesaField;
        
        private string idunidadestrategicanegocioField;
        
        private unidad[] unidadesField;
        
        /// <remarks/>
        public string tipoenvio {
            get {
                return this.tipoenvioField;
            }
            set {
                this.tipoenvioField = value;
            }
        }
        
        /// <remarks/>
        public string idciudadorigen {
            get {
                return this.idciudadorigenField;
            }
            set {
                this.idciudadorigenField = value;
            }
        }
        
        /// <remarks/>
        public string idciudaddestino {
            get {
                return this.idciudaddestinoField;
            }
            set {
                this.idciudaddestinoField = value;
            }
        }
        
        /// <remarks/>
        public string valormercancia {
            get {
                return this.valormercanciaField;
            }
            set {
                this.valormercanciaField = value;
            }
        }
        
        /// <remarks/>
        public string boomerang {
            get {
                return this.boomerangField;
            }
            set {
                this.boomerangField = value;
            }
        }
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string fecharemesa {
            get {
                return this.fecharemesaField;
            }
            set {
                this.fecharemesaField = value;
            }
        }
        
        /// <remarks/>
        public string idunidadestrategicanegocio {
            get {
                return this.idunidadestrategicanegocioField;
            }
            set {
                this.idunidadestrategicanegocioField = value;
            }
        }
        
        /// <remarks/>
        public unidad[] unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class Ciudad {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        private string codigodaneField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
        
        /// <remarks/>
        public string codigodane {
            get {
                return this.codigodaneField;
            }
            set {
                this.codigodaneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientes.tcc.com.co/")]
    public partial class ciudadesRespuesta {
        
        private Ciudad[] ciudadesorigenField;
        
        private Ciudad[] ciudadesdestinoField;
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        public Ciudad[] ciudadesorigen {
            get {
                return this.ciudadesorigenField;
            }
            set {
                this.ciudadesorigenField = value;
            }
        }
        
        /// <remarks/>
        public Ciudad[] ciudadesdestino {
            get {
                return this.ciudadesdestinoField;
            }
            set {
                this.ciudadesdestinoField = value;
            }
        }
        
        /// <remarks/>
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void LiquidaDespachoCompletedEventHandler(object sender, LiquidaDespachoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LiquidaDespachoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LiquidaDespachoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Liquidacion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void LiquidaDespacho2CompletedEventHandler(object sender, LiquidaDespacho2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LiquidaDespacho2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LiquidaDespacho2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Liquidacion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultarMaestroCiudadesCompletedEventHandler(object sender, consultarMaestroCiudadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarMaestroCiudadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarMaestroCiudadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ciudadesRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ciudadesRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultarliquidacionCompletedEventHandler(object sender, consultarliquidacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarliquidacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarliquidacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LiquidacionRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LiquidacionRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void HabilitarCotizacionAcuerdosCompletedEventHandler(object sender, HabilitarCotizacionAcuerdosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HabilitarCotizacionAcuerdosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HabilitarCotizacionAcuerdosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public clsOpcion[] Opciones {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsOpcion[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public clsCuenta[] Cuentas {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsCuenta[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int Respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
}

#pragma warning restore 1591