//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluLogisticsService.BluServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BluServiceReference.WebServiceFPSoap")]
    public interface WebServiceFPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.AutenticarResponse Autenticar(BluLogisticsService.BluServiceReference.AutenticarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.AutenticarResponse> AutenticarAsync(BluLogisticsService.BluServiceReference.AutenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarCiudadesDestino", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoResponse SolicitarCiudadesDestino(BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarCiudadesDestino", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoResponse> SolicitarCiudadesDestinoAsync(BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarTablas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.SolicitarTablasResponse SolicitarTablas(BluLogisticsService.BluServiceReference.SolicitarTablasRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarTablas", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.SolicitarTablasResponse> SolicitarTablasAsync(BluLogisticsService.BluServiceReference.SolicitarTablasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarFactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.ConsultarFacturaResponse ConsultarFactura(BluLogisticsService.BluServiceReference.ConsultarFacturaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.ConsultarFacturaResponse> ConsultarFacturaAsync(BluLogisticsService.BluServiceReference.ConsultarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarFactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.RegistrarFacturaResponse RegistrarFactura(BluLogisticsService.BluServiceReference.RegistrarFacturaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.RegistrarFacturaResponse> RegistrarFacturaAsync(BluLogisticsService.BluServiceReference.RegistrarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreLiquidacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.GetPreLiquidacionResponse GetPreLiquidacion(BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreLiquidacion", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.GetPreLiquidacionResponse> GetPreLiquidacionAsync(BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest request);
        
        // CODEGEN: Generating message contract since message ConsultaEtiquetaPdfRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEtiquetaPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse ConsultaEtiquetaPdf(BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEtiquetaPdf", ReplyAction="*")]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse> ConsultaEtiquetaPdfAsync(BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EEncabezado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private string terminalField;
        
        private string versionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
                this.RaisePropertyChanged("Terminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class viewLiquidacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal valorFleteField;
        
        private decimal costoManejoField;
        
        private decimal tarifaField;
        
        private decimal descuentoField;
        
        private string observacionField;
        
        private decimal totalFleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal valorFlete {
            get {
                return this.valorFleteField;
            }
            set {
                this.valorFleteField = value;
                this.RaisePropertyChanged("valorFlete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal costoManejo {
            get {
                return this.costoManejoField;
            }
            set {
                this.costoManejoField = value;
                this.RaisePropertyChanged("costoManejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("Tarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("Descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal TotalFlete {
            get {
                return this.totalFleteField;
            }
            set {
                this.totalFleteField = value;
                this.RaisePropertyChanged("TotalFlete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EFacturaKiosco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idFacturaField;
        
        private string identificacionField;
        
        private string nombreClienteField;
        
        private string direccionClienteField;
        
        private string telefonoClienteField;
        
        private string nombreDestinoField;
        
        private string direccionDestinoField;
        
        private string telefonoDestinoField;
        
        private string celularDestinoField;
        
        private string idOrigenField;
        
        private string idDestinoField;
        
        private System.Nullable<float> kilosField;
        
        private System.Nullable<int> kilosXvolumenField;
        
        private string contenidoField;
        
        private System.Nullable<int> valorDeclaradoField;
        
        private System.Nullable<int> totalField;
        
        private System.Nullable<int> valorFleteField;
        
        private System.Nullable<int> manejoField;
        
        private System.Nullable<int> cantidadField;
        
        private string obsField;
        
        private string formaPagoField;
        
        private decimal idCuentaClienteField;
        
        private string referenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdFactura {
            get {
                return this.idFacturaField;
            }
            set {
                this.idFacturaField = value;
                this.RaisePropertyChanged("IdFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("Identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("NombreCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DireccionCliente {
            get {
                return this.direccionClienteField;
            }
            set {
                this.direccionClienteField = value;
                this.RaisePropertyChanged("DireccionCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TelefonoCliente {
            get {
                return this.telefonoClienteField;
            }
            set {
                this.telefonoClienteField = value;
                this.RaisePropertyChanged("TelefonoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NombreDestino {
            get {
                return this.nombreDestinoField;
            }
            set {
                this.nombreDestinoField = value;
                this.RaisePropertyChanged("NombreDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DireccionDestino {
            get {
                return this.direccionDestinoField;
            }
            set {
                this.direccionDestinoField = value;
                this.RaisePropertyChanged("DireccionDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TelefonoDestino {
            get {
                return this.telefonoDestinoField;
            }
            set {
                this.telefonoDestinoField = value;
                this.RaisePropertyChanged("TelefonoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CelularDestino {
            get {
                return this.celularDestinoField;
            }
            set {
                this.celularDestinoField = value;
                this.RaisePropertyChanged("CelularDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IdOrigen {
            get {
                return this.idOrigenField;
            }
            set {
                this.idOrigenField = value;
                this.RaisePropertyChanged("IdOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IdDestino {
            get {
                return this.idDestinoField;
            }
            set {
                this.idDestinoField = value;
                this.RaisePropertyChanged("IdDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<float> Kilos {
            get {
                return this.kilosField;
            }
            set {
                this.kilosField = value;
                this.RaisePropertyChanged("Kilos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> KilosXvolumen {
            get {
                return this.kilosXvolumenField;
            }
            set {
                this.kilosXvolumenField = value;
                this.RaisePropertyChanged("KilosXvolumen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("Contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> ValorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
                this.RaisePropertyChanged("ValorDeclarado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> ValorFlete {
            get {
                return this.valorFleteField;
            }
            set {
                this.valorFleteField = value;
                this.RaisePropertyChanged("ValorFlete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> Manejo {
            get {
                return this.manejoField;
            }
            set {
                this.manejoField = value;
                this.RaisePropertyChanged("Manejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
                this.RaisePropertyChanged("Obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("FormaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal IdCuentaCliente {
            get {
                return this.idCuentaClienteField;
            }
            set {
                this.idCuentaClienteField = value;
                this.RaisePropertyChanged("IdCuentaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("Referencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EFacturaKioscoDetalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guiaField;
        
        private string linea1Field;
        
        private string linea2Field;
        
        private string linea3Field;
        
        private string linea4Field;
        
        private string linea5Field;
        
        private string linea6Field;
        
        private string linea7Field;
        
        private string linea8Field;
        
        private string linea9Field;
        
        private string resolucionField;
        
        private string facturaField;
        
        private System.DateTime fechaFacturaField;
        
        private string vendedorField;
        
        private string nombreClienteField;
        
        private string identificacionClienteField;
        
        private string direccionClienteField;
        
        private string telefonoClienteField;
        
        private string nombreDestinoField;
        
        private string direccionDestinoField;
        
        private string telefonoDestinoField;
        
        private string celularDestinoField;
        
        private string ciudadOrigenField;
        
        private string ciudadDestinoField;
        
        private string departDestinoField;
        
        private string departOrigenField;
        
        private System.Nullable<float> kilosField;
        
        private System.Nullable<int> kilosXvolumenField;
        
        private string contenidoField;
        
        private System.Nullable<int> valorDeclaradoField;
        
        private System.Nullable<int> totalField;
        
        private System.Nullable<int> valorFleteField;
        
        private System.Nullable<int> manejoField;
        
        private System.Nullable<int> unidadesField;
        
        private string obsField;
        
        private string formaPagoField;
        
        private decimal idCuentaClienteField;
        
        private string referenciaField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Guia {
            get {
                return this.guiaField;
            }
            set {
                this.guiaField = value;
                this.RaisePropertyChanged("Guia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Linea1 {
            get {
                return this.linea1Field;
            }
            set {
                this.linea1Field = value;
                this.RaisePropertyChanged("Linea1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Linea2 {
            get {
                return this.linea2Field;
            }
            set {
                this.linea2Field = value;
                this.RaisePropertyChanged("Linea2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Linea3 {
            get {
                return this.linea3Field;
            }
            set {
                this.linea3Field = value;
                this.RaisePropertyChanged("Linea3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Linea4 {
            get {
                return this.linea4Field;
            }
            set {
                this.linea4Field = value;
                this.RaisePropertyChanged("Linea4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Linea5 {
            get {
                return this.linea5Field;
            }
            set {
                this.linea5Field = value;
                this.RaisePropertyChanged("Linea5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Linea6 {
            get {
                return this.linea6Field;
            }
            set {
                this.linea6Field = value;
                this.RaisePropertyChanged("Linea6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Linea7 {
            get {
                return this.linea7Field;
            }
            set {
                this.linea7Field = value;
                this.RaisePropertyChanged("Linea7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Linea8 {
            get {
                return this.linea8Field;
            }
            set {
                this.linea8Field = value;
                this.RaisePropertyChanged("Linea8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Linea9 {
            get {
                return this.linea9Field;
            }
            set {
                this.linea9Field = value;
                this.RaisePropertyChanged("Linea9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Resolucion {
            get {
                return this.resolucionField;
            }
            set {
                this.resolucionField = value;
                this.RaisePropertyChanged("Resolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
                this.RaisePropertyChanged("Factura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime FechaFactura {
            get {
                return this.fechaFacturaField;
            }
            set {
                this.fechaFacturaField = value;
                this.RaisePropertyChanged("FechaFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
                this.RaisePropertyChanged("Vendedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("NombreCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string IdentificacionCliente {
            get {
                return this.identificacionClienteField;
            }
            set {
                this.identificacionClienteField = value;
                this.RaisePropertyChanged("IdentificacionCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DireccionCliente {
            get {
                return this.direccionClienteField;
            }
            set {
                this.direccionClienteField = value;
                this.RaisePropertyChanged("DireccionCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TelefonoCliente {
            get {
                return this.telefonoClienteField;
            }
            set {
                this.telefonoClienteField = value;
                this.RaisePropertyChanged("TelefonoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NombreDestino {
            get {
                return this.nombreDestinoField;
            }
            set {
                this.nombreDestinoField = value;
                this.RaisePropertyChanged("NombreDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DireccionDestino {
            get {
                return this.direccionDestinoField;
            }
            set {
                this.direccionDestinoField = value;
                this.RaisePropertyChanged("DireccionDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string TelefonoDestino {
            get {
                return this.telefonoDestinoField;
            }
            set {
                this.telefonoDestinoField = value;
                this.RaisePropertyChanged("TelefonoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CelularDestino {
            get {
                return this.celularDestinoField;
            }
            set {
                this.celularDestinoField = value;
                this.RaisePropertyChanged("CelularDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CiudadOrigen {
            get {
                return this.ciudadOrigenField;
            }
            set {
                this.ciudadOrigenField = value;
                this.RaisePropertyChanged("CiudadOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CiudadDestino {
            get {
                return this.ciudadDestinoField;
            }
            set {
                this.ciudadDestinoField = value;
                this.RaisePropertyChanged("CiudadDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DepartDestino {
            get {
                return this.departDestinoField;
            }
            set {
                this.departDestinoField = value;
                this.RaisePropertyChanged("DepartDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DepartOrigen {
            get {
                return this.departOrigenField;
            }
            set {
                this.departOrigenField = value;
                this.RaisePropertyChanged("DepartOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<float> Kilos {
            get {
                return this.kilosField;
            }
            set {
                this.kilosField = value;
                this.RaisePropertyChanged("Kilos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> KilosXvolumen {
            get {
                return this.kilosXvolumenField;
            }
            set {
                this.kilosXvolumenField = value;
                this.RaisePropertyChanged("KilosXvolumen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("Contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> ValorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
                this.RaisePropertyChanged("ValorDeclarado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> ValorFlete {
            get {
                return this.valorFleteField;
            }
            set {
                this.valorFleteField = value;
                this.RaisePropertyChanged("ValorFlete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<int> Manejo {
            get {
                return this.manejoField;
            }
            set {
                this.manejoField = value;
                this.RaisePropertyChanged("Manejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<int> Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
                this.RaisePropertyChanged("Obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("FormaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal IdCuentaCliente {
            get {
                return this.idCuentaClienteField;
            }
            set {
                this.idCuentaClienteField = value;
                this.RaisePropertyChanged("IdCuentaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("Referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ETablas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int indiceTablaField;
        
        private string idPropioField;
        
        private string descripcionField;
        
        private string campo1Field;
        
        private string campo2Field;
        
        private string campo3Field;
        
        private string campo4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IndiceTabla {
            get {
                return this.indiceTablaField;
            }
            set {
                this.indiceTablaField = value;
                this.RaisePropertyChanged("IndiceTabla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdPropio {
            get {
                return this.idPropioField;
            }
            set {
                this.idPropioField = value;
                this.RaisePropertyChanged("IdPropio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Campo1 {
            get {
                return this.campo1Field;
            }
            set {
                this.campo1Field = value;
                this.RaisePropertyChanged("Campo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Campo2 {
            get {
                return this.campo2Field;
            }
            set {
                this.campo2Field = value;
                this.RaisePropertyChanged("Campo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Campo3 {
            get {
                return this.campo3Field;
            }
            set {
                this.campo3Field = value;
                this.RaisePropertyChanged("Campo3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Campo4 {
            get {
                return this.campo4Field;
            }
            set {
                this.campo4Field = value;
                this.RaisePropertyChanged("Campo4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ECiudades : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idCiudadField;
        
        private string nombreField;
        
        private string departamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("IdCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("Departamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string rolesField;
        
        private string identifiacionField;
        
        private string codCiudadSurcursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("Roles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Identifiacion {
            get {
                return this.identifiacionField;
            }
            set {
                this.identifiacionField = value;
                this.RaisePropertyChanged("Identifiacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodCiudadSurcursal {
            get {
                return this.codCiudadSurcursalField;
            }
            set {
                this.codCiudadSurcursalField = value;
                this.RaisePropertyChanged("CodCiudadSurcursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EUsuario usuario;
        
        public AutenticarRequest() {
        }
        
        public AutenticarRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EUsuario usuario) {
            this.EEncabezado = EEncabezado;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError AutenticarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.EUsuario usuario;
        
        public AutenticarResponse() {
        }
        
        public AutenticarResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError AutenticarResult, BluLogisticsService.BluServiceReference.EUsuario usuario) {
            this.EEncabezado = EEncabezado;
            this.AutenticarResult = AutenticarResult;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarCiudadesDestino", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SolicitarCiudadesDestinoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.ECiudades[] ciudades;
        
        public SolicitarCiudadesDestinoRequest() {
        }
        
        public SolicitarCiudadesDestinoRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.ECiudades[] ciudades) {
            this.EEncabezado = EEncabezado;
            this.ciudades = ciudades;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarCiudadesDestinoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SolicitarCiudadesDestinoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError SolicitarCiudadesDestinoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.ECiudades[] ciudades;
        
        public SolicitarCiudadesDestinoResponse() {
        }
        
        public SolicitarCiudadesDestinoResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError SolicitarCiudadesDestinoResult, BluLogisticsService.BluServiceReference.ECiudades[] ciudades) {
            this.EEncabezado = EEncabezado;
            this.SolicitarCiudadesDestinoResult = SolicitarCiudadesDestinoResult;
            this.ciudades = ciudades;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarTablas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SolicitarTablasRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.ETablas[] tablas;
        
        public SolicitarTablasRequest() {
        }
        
        public SolicitarTablasRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.ETablas[] tablas) {
            this.EEncabezado = EEncabezado;
            this.tablas = tablas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarTablasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SolicitarTablasResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError SolicitarTablasResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.ETablas[] tablas;
        
        public SolicitarTablasResponse() {
        }
        
        public SolicitarTablasResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError SolicitarTablasResult, BluLogisticsService.BluServiceReference.ETablas[] tablas) {
            this.EEncabezado = EEncabezado;
            this.SolicitarTablasResult = SolicitarTablasResult;
            this.tablas = tablas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarFactura", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarFacturaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string factura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.EFacturaKioscoDetalle FacturaDetalle;
        
        public ConsultarFacturaRequest() {
        }
        
        public ConsultarFacturaRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string factura, BluLogisticsService.BluServiceReference.EFacturaKioscoDetalle FacturaDetalle) {
            this.EEncabezado = EEncabezado;
            this.factura = factura;
            this.FacturaDetalle = FacturaDetalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarFacturaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarFacturaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError ConsultarFacturaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.EFacturaKioscoDetalle FacturaDetalle;
        
        public ConsultarFacturaResponse() {
        }
        
        public ConsultarFacturaResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError ConsultarFacturaResult, BluLogisticsService.BluServiceReference.EFacturaKioscoDetalle FacturaDetalle) {
            this.EEncabezado = EEncabezado;
            this.ConsultarFacturaResult = ConsultarFacturaResult;
            this.FacturaDetalle = FacturaDetalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarFactura", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarFacturaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EFacturaKiosco Factura;
        
        public RegistrarFacturaRequest() {
        }
        
        public RegistrarFacturaRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EFacturaKiosco Factura) {
            this.EEncabezado = EEncabezado;
            this.Factura = Factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarFacturaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarFacturaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError RegistrarFacturaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.EFacturaKiosco Factura;
        
        public RegistrarFacturaResponse() {
        }
        
        public RegistrarFacturaResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError RegistrarFacturaResult, BluLogisticsService.BluServiceReference.EFacturaKiosco Factura) {
            this.EEncabezado = EEncabezado;
            this.RegistrarFacturaResult = RegistrarFacturaResult;
            this.Factura = Factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPreLiquidacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPreLiquidacionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal cuentaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal declarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal unidades;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public decimal kilos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal volumen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string codeOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string codeDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public BluLogisticsService.BluServiceReference.viewLiquidacion Liquidacion;
        
        public GetPreLiquidacionRequest() {
        }
        
        public GetPreLiquidacionRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, decimal cuentaId, decimal declarado, decimal unidades, decimal kilos, decimal volumen, string codeOrigen, string codeDestino, BluLogisticsService.BluServiceReference.viewLiquidacion Liquidacion) {
            this.EEncabezado = EEncabezado;
            this.cuentaId = cuentaId;
            this.declarado = declarado;
            this.unidades = unidades;
            this.kilos = kilos;
            this.volumen = volumen;
            this.codeOrigen = codeOrigen;
            this.codeDestino = codeDestino;
            this.Liquidacion = Liquidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPreLiquidacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPreLiquidacionResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BluLogisticsService.BluServiceReference.EError GetPreLiquidacionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BluLogisticsService.BluServiceReference.viewLiquidacion Liquidacion;
        
        public GetPreLiquidacionResponse() {
        }
        
        public GetPreLiquidacionResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, BluLogisticsService.BluServiceReference.EError GetPreLiquidacionResult, BluLogisticsService.BluServiceReference.viewLiquidacion Liquidacion) {
            this.EEncabezado = EEncabezado;
            this.GetPreLiquidacionResult = GetPreLiquidacionResult;
            this.Liquidacion = Liquidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEtiquetaPdf", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEtiquetaPdfRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string factura;
        
        public ConsultaEtiquetaPdfRequest() {
        }
        
        public ConsultaEtiquetaPdfRequest(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string factura) {
            this.EEncabezado = EEncabezado;
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEtiquetaPdfResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEtiquetaPdfResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BluLogisticsService.BluServiceReference.EEncabezado EEncabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ConsultaEtiquetaPdfResult;
        
        public ConsultaEtiquetaPdfResponse() {
        }
        
        public ConsultaEtiquetaPdfResponse(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string ConsultaEtiquetaPdfResult) {
            this.EEncabezado = EEncabezado;
            this.ConsultaEtiquetaPdfResult = ConsultaEtiquetaPdfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFPSoapChannel : BluLogisticsService.BluServiceReference.WebServiceFPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFPSoapClient : System.ServiceModel.ClientBase<BluLogisticsService.BluServiceReference.WebServiceFPSoap>, BluLogisticsService.BluServiceReference.WebServiceFPSoap {
        
        public WebServiceFPSoapClient() {
        }
        
        public WebServiceFPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.AutenticarResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.Autenticar(BluLogisticsService.BluServiceReference.AutenticarRequest request) {
            return base.Channel.Autenticar(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError Autenticar(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, ref BluLogisticsService.BluServiceReference.EUsuario usuario) {
            BluLogisticsService.BluServiceReference.AutenticarRequest inValue = new BluLogisticsService.BluServiceReference.AutenticarRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.usuario = usuario;
            BluLogisticsService.BluServiceReference.AutenticarResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).Autenticar(inValue);
            EEncabezado = retVal.EEncabezado;
            usuario = retVal.usuario;
            return retVal.AutenticarResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.AutenticarResponse> AutenticarAsync(BluLogisticsService.BluServiceReference.AutenticarRequest request) {
            return base.Channel.AutenticarAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.SolicitarCiudadesDestino(BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest request) {
            return base.Channel.SolicitarCiudadesDestino(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError SolicitarCiudadesDestino(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, ref BluLogisticsService.BluServiceReference.ECiudades[] ciudades) {
            BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest inValue = new BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.ciudades = ciudades;
            BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).SolicitarCiudadesDestino(inValue);
            EEncabezado = retVal.EEncabezado;
            ciudades = retVal.ciudades;
            return retVal.SolicitarCiudadesDestinoResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoResponse> SolicitarCiudadesDestinoAsync(BluLogisticsService.BluServiceReference.SolicitarCiudadesDestinoRequest request) {
            return base.Channel.SolicitarCiudadesDestinoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.SolicitarTablasResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.SolicitarTablas(BluLogisticsService.BluServiceReference.SolicitarTablasRequest request) {
            return base.Channel.SolicitarTablas(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError SolicitarTablas(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, ref BluLogisticsService.BluServiceReference.ETablas[] tablas) {
            BluLogisticsService.BluServiceReference.SolicitarTablasRequest inValue = new BluLogisticsService.BluServiceReference.SolicitarTablasRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.tablas = tablas;
            BluLogisticsService.BluServiceReference.SolicitarTablasResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).SolicitarTablas(inValue);
            EEncabezado = retVal.EEncabezado;
            tablas = retVal.tablas;
            return retVal.SolicitarTablasResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.SolicitarTablasResponse> SolicitarTablasAsync(BluLogisticsService.BluServiceReference.SolicitarTablasRequest request) {
            return base.Channel.SolicitarTablasAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.ConsultarFacturaResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.ConsultarFactura(BluLogisticsService.BluServiceReference.ConsultarFacturaRequest request) {
            return base.Channel.ConsultarFactura(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError ConsultarFactura(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string factura, ref BluLogisticsService.BluServiceReference.EFacturaKioscoDetalle FacturaDetalle) {
            BluLogisticsService.BluServiceReference.ConsultarFacturaRequest inValue = new BluLogisticsService.BluServiceReference.ConsultarFacturaRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.factura = factura;
            inValue.FacturaDetalle = FacturaDetalle;
            BluLogisticsService.BluServiceReference.ConsultarFacturaResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).ConsultarFactura(inValue);
            EEncabezado = retVal.EEncabezado;
            FacturaDetalle = retVal.FacturaDetalle;
            return retVal.ConsultarFacturaResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.ConsultarFacturaResponse> ConsultarFacturaAsync(BluLogisticsService.BluServiceReference.ConsultarFacturaRequest request) {
            return base.Channel.ConsultarFacturaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.RegistrarFacturaResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.RegistrarFactura(BluLogisticsService.BluServiceReference.RegistrarFacturaRequest request) {
            return base.Channel.RegistrarFactura(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError RegistrarFactura(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, ref BluLogisticsService.BluServiceReference.EFacturaKiosco Factura) {
            BluLogisticsService.BluServiceReference.RegistrarFacturaRequest inValue = new BluLogisticsService.BluServiceReference.RegistrarFacturaRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.Factura = Factura;
            BluLogisticsService.BluServiceReference.RegistrarFacturaResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).RegistrarFactura(inValue);
            EEncabezado = retVal.EEncabezado;
            Factura = retVal.Factura;
            return retVal.RegistrarFacturaResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.RegistrarFacturaResponse> RegistrarFacturaAsync(BluLogisticsService.BluServiceReference.RegistrarFacturaRequest request) {
            return base.Channel.RegistrarFacturaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.GetPreLiquidacionResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.GetPreLiquidacion(BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest request) {
            return base.Channel.GetPreLiquidacion(request);
        }
        
        public BluLogisticsService.BluServiceReference.EError GetPreLiquidacion(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, decimal cuentaId, decimal declarado, decimal unidades, decimal kilos, decimal volumen, string codeOrigen, string codeDestino, ref BluLogisticsService.BluServiceReference.viewLiquidacion Liquidacion) {
            BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest inValue = new BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.cuentaId = cuentaId;
            inValue.declarado = declarado;
            inValue.unidades = unidades;
            inValue.kilos = kilos;
            inValue.volumen = volumen;
            inValue.codeOrigen = codeOrigen;
            inValue.codeDestino = codeDestino;
            inValue.Liquidacion = Liquidacion;
            BluLogisticsService.BluServiceReference.GetPreLiquidacionResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).GetPreLiquidacion(inValue);
            EEncabezado = retVal.EEncabezado;
            Liquidacion = retVal.Liquidacion;
            return retVal.GetPreLiquidacionResult;
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.GetPreLiquidacionResponse> GetPreLiquidacionAsync(BluLogisticsService.BluServiceReference.GetPreLiquidacionRequest request) {
            return base.Channel.GetPreLiquidacionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse BluLogisticsService.BluServiceReference.WebServiceFPSoap.ConsultaEtiquetaPdf(BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest request) {
            return base.Channel.ConsultaEtiquetaPdf(request);
        }
        
        public string ConsultaEtiquetaPdf(ref BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string factura) {
            BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest inValue = new BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.factura = factura;
            BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse retVal = ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).ConsultaEtiquetaPdf(inValue);
            EEncabezado = retVal.EEncabezado;
            return retVal.ConsultaEtiquetaPdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse> BluLogisticsService.BluServiceReference.WebServiceFPSoap.ConsultaEtiquetaPdfAsync(BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest request) {
            return base.Channel.ConsultaEtiquetaPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfResponse> ConsultaEtiquetaPdfAsync(BluLogisticsService.BluServiceReference.EEncabezado EEncabezado, string factura) {
            BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest inValue = new BluLogisticsService.BluServiceReference.ConsultaEtiquetaPdfRequest();
            inValue.EEncabezado = EEncabezado;
            inValue.factura = factura;
            return ((BluLogisticsService.BluServiceReference.WebServiceFPSoap)(this)).ConsultaEtiquetaPdfAsync(inValue);
        }
    }
}
