//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TCCService.co.com.tcc.clientes.remesas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsDespachosSoap", Namespace="http://xmlns.oracle.com/OSB_ClientesApi/RemesaApi/wsDespachos")]
    public partial class wsDespachosSoapQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback grabardespacho7OperationCompleted;
        
        private System.Threading.SendOrPostCallback anulardespachoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarinformacionremesaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsDespachosSoapQSService() {
            this.Url = global::TCCService.Properties.Settings.Default.TCCService_co_com_tcc_clientes_remesas_wsDespachosSoapQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event grabardespacho7CompletedEventHandler grabardespacho7Completed;
        
        /// <remarks/>
        public event anulardespachoCompletedEventHandler anulardespachoCompleted;
        
        /// <remarks/>
        public event consultarinformacionremesaCompletedEventHandler consultarinformacionremesaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("grabardespachos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("grabardespacho7respuesta", Namespace="http://www.tcc.com.co/xsd/remesa/")]
        public grabardespacho7respuesta grabardespacho7([System.Xml.Serialization.XmlElementAttribute("grabardespacho7", Namespace="http://www.tcc.com.co/xsd/remesa/")] grabardespacho7 grabardespacho71) {
            object[] results = this.Invoke("grabardespacho7", new object[] {
                        grabardespacho71});
            return ((grabardespacho7respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void grabardespacho7Async(grabardespacho7 grabardespacho71) {
            this.grabardespacho7Async(grabardespacho71, null);
        }
        
        /// <remarks/>
        public void grabardespacho7Async(grabardespacho7 grabardespacho71, object userState) {
            if ((this.grabardespacho7OperationCompleted == null)) {
                this.grabardespacho7OperationCompleted = new System.Threading.SendOrPostCallback(this.Ongrabardespacho7OperationCompleted);
            }
            this.InvokeAsync("grabardespacho7", new object[] {
                        grabardespacho71}, this.grabardespacho7OperationCompleted, userState);
        }
        
        private void Ongrabardespacho7OperationCompleted(object arg) {
            if ((this.grabardespacho7Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grabardespacho7Completed(this, new grabardespacho7CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("anulardespacho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("anulardespachorespuesta", Namespace="http://www.tcc.com.co/xsd/remesa/")]
        public anulardespachorespuesta anulardespacho([System.Xml.Serialization.XmlElementAttribute("anulardespacho", Namespace="http://www.tcc.com.co/xsd/remesa/")] anulardespacho anulardespacho1) {
            object[] results = this.Invoke("anulardespacho", new object[] {
                        anulardespacho1});
            return ((anulardespachorespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void anulardespachoAsync(anulardespacho anulardespacho1) {
            this.anulardespachoAsync(anulardespacho1, null);
        }
        
        /// <remarks/>
        public void anulardespachoAsync(anulardespacho anulardespacho1, object userState) {
            if ((this.anulardespachoOperationCompleted == null)) {
                this.anulardespachoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnanulardespachoOperationCompleted);
            }
            this.InvokeAsync("anulardespacho", new object[] {
                        anulardespacho1}, this.anulardespachoOperationCompleted, userState);
        }
        
        private void OnanulardespachoOperationCompleted(object arg) {
            if ((this.anulardespachoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.anulardespachoCompleted(this, new anulardespachoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xmlns.oracle.com/OSB_ClientesApi/RemesaApi/wsDespachos/consultarinformacio" +
            "nremesa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultartrazabilidadremesarespuesta", Namespace="http://www.tcc.com.co/xsd")]
        public consultartrazabilidadremesarespuesta consultarinformacionremesa([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tcc.com.co/xsd/remesa/")] consultartrazabilidadremesa consultartrazabilidadremesa) {
            object[] results = this.Invoke("consultarinformacionremesa", new object[] {
                        consultartrazabilidadremesa});
            return ((consultartrazabilidadremesarespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void consultarinformacionremesaAsync(consultartrazabilidadremesa consultartrazabilidadremesa) {
            this.consultarinformacionremesaAsync(consultartrazabilidadremesa, null);
        }
        
        /// <remarks/>
        public void consultarinformacionremesaAsync(consultartrazabilidadremesa consultartrazabilidadremesa, object userState) {
            if ((this.consultarinformacionremesaOperationCompleted == null)) {
                this.consultarinformacionremesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarinformacionremesaOperationCompleted);
            }
            this.InvokeAsync("consultarinformacionremesa", new object[] {
                        consultartrazabilidadremesa}, this.consultarinformacionremesaOperationCompleted, userState);
        }
        
        private void OnconsultarinformacionremesaOperationCompleted(object arg) {
            if ((this.consultarinformacionremesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarinformacionremesaCompleted(this, new consultarinformacionremesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class grabardespacho7 {
        
        private remesa despachoField;
        
        /// <remarks/>
        public remesa despacho {
            get {
                return this.despachoField;
            }
            set {
                this.despachoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class remesa {
        
        private string claveField;
        
        private string numerorelacionField;
        
        private string fechahorarelacionField;
        
        private recogida solicitudrecogidaField;
        
        private string unidadnegocioField;
        
        private string numeroremesaField;
        
        private string fechadespachoField;
        
        private string cuentaremitenteField;
        
        private string tipoidentificacionremitenteField;
        
        private string identificacionremitenteField;
        
        private string sederemitenteField;
        
        private string primernombreremitenteField;
        
        private string segundonombreremitenteField;
        
        private string primerapellidoremitenteField;
        
        private string segundoapellidoremitenteField;
        
        private string razonsocialremitenteField;
        
        private string naturalezaremitenteField;
        
        private string direccionremitenteField;
        
        private string contactoremitenteField;
        
        private string emailremitenteField;
        
        private string telefonoremitenteField;
        
        private string ciudadorigenField;
        
        private string tipoidentificaciondestinatarioField;
        
        private string identificaciondestinatarioField;
        
        private string sededestinatarioField;
        
        private string primernombredestinatarioField;
        
        private string segundonombredestinatarioField;
        
        private string primerapellidodestinatarioField;
        
        private string segundoapellidodestinatarioField;
        
        private string razonsocialdestinatarioField;
        
        private string naturalezadestinatarioField;
        
        private string direcciondestinatarioField;
        
        private string contactodestinatarioField;
        
        private string emaildestinatarioField;
        
        private string telefonodestinatarioField;
        
        private string ciudaddestinatarioField;
        
        private string barriodestinatarioField;
        
        private string totalpesoField;
        
        private string totalpesovolumenField;
        
        private string totalvalormercanciaField;
        
        private string formapagoField;
        
        private string observacionesField;
        
        private string llevabodegaField;
        
        private string recogebodegaField;
        
        private string centrocostosField;
        
        private string totalvalorproductoField;
        
        private string tiposervicioField;
        
        private unidad[] unidadField;
        
        private documentoreferencia[] documentoreferenciaField;
        
        private string numeroreferenciaclienteField;
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string numerorelacion {
            get {
                return this.numerorelacionField;
            }
            set {
                this.numerorelacionField = value;
            }
        }
        
        /// <remarks/>
        public string fechahorarelacion {
            get {
                return this.fechahorarelacionField;
            }
            set {
                this.fechahorarelacionField = value;
            }
        }
        
        /// <remarks/>
        public recogida solicitudrecogida {
            get {
                return this.solicitudrecogidaField;
            }
            set {
                this.solicitudrecogidaField = value;
            }
        }
        
        /// <remarks/>
        public string unidadnegocio {
            get {
                return this.unidadnegocioField;
            }
            set {
                this.unidadnegocioField = value;
            }
        }
        
        /// <remarks/>
        public string numeroremesa {
            get {
                return this.numeroremesaField;
            }
            set {
                this.numeroremesaField = value;
            }
        }
        
        /// <remarks/>
        public string fechadespacho {
            get {
                return this.fechadespachoField;
            }
            set {
                this.fechadespachoField = value;
            }
        }
        
        /// <remarks/>
        public string cuentaremitente {
            get {
                return this.cuentaremitenteField;
            }
            set {
                this.cuentaremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string tipoidentificacionremitente {
            get {
                return this.tipoidentificacionremitenteField;
            }
            set {
                this.tipoidentificacionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string identificacionremitente {
            get {
                return this.identificacionremitenteField;
            }
            set {
                this.identificacionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string sederemitente {
            get {
                return this.sederemitenteField;
            }
            set {
                this.sederemitenteField = value;
            }
        }
        
        /// <remarks/>
        public string primernombreremitente {
            get {
                return this.primernombreremitenteField;
            }
            set {
                this.primernombreremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string segundonombreremitente {
            get {
                return this.segundonombreremitenteField;
            }
            set {
                this.segundonombreremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string primerapellidoremitente {
            get {
                return this.primerapellidoremitenteField;
            }
            set {
                this.primerapellidoremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string segundoapellidoremitente {
            get {
                return this.segundoapellidoremitenteField;
            }
            set {
                this.segundoapellidoremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string razonsocialremitente {
            get {
                return this.razonsocialremitenteField;
            }
            set {
                this.razonsocialremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string naturalezaremitente {
            get {
                return this.naturalezaremitenteField;
            }
            set {
                this.naturalezaremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string direccionremitente {
            get {
                return this.direccionremitenteField;
            }
            set {
                this.direccionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string contactoremitente {
            get {
                return this.contactoremitenteField;
            }
            set {
                this.contactoremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string emailremitente {
            get {
                return this.emailremitenteField;
            }
            set {
                this.emailremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string telefonoremitente {
            get {
                return this.telefonoremitenteField;
            }
            set {
                this.telefonoremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string ciudadorigen {
            get {
                return this.ciudadorigenField;
            }
            set {
                this.ciudadorigenField = value;
            }
        }
        
        /// <remarks/>
        public string tipoidentificaciondestinatario {
            get {
                return this.tipoidentificaciondestinatarioField;
            }
            set {
                this.tipoidentificaciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string identificaciondestinatario {
            get {
                return this.identificaciondestinatarioField;
            }
            set {
                this.identificaciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string sededestinatario {
            get {
                return this.sededestinatarioField;
            }
            set {
                this.sededestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string primernombredestinatario {
            get {
                return this.primernombredestinatarioField;
            }
            set {
                this.primernombredestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string segundonombredestinatario {
            get {
                return this.segundonombredestinatarioField;
            }
            set {
                this.segundonombredestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string primerapellidodestinatario {
            get {
                return this.primerapellidodestinatarioField;
            }
            set {
                this.primerapellidodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string segundoapellidodestinatario {
            get {
                return this.segundoapellidodestinatarioField;
            }
            set {
                this.segundoapellidodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string razonsocialdestinatario {
            get {
                return this.razonsocialdestinatarioField;
            }
            set {
                this.razonsocialdestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string naturalezadestinatario {
            get {
                return this.naturalezadestinatarioField;
            }
            set {
                this.naturalezadestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string direcciondestinatario {
            get {
                return this.direcciondestinatarioField;
            }
            set {
                this.direcciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string contactodestinatario {
            get {
                return this.contactodestinatarioField;
            }
            set {
                this.contactodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string emaildestinatario {
            get {
                return this.emaildestinatarioField;
            }
            set {
                this.emaildestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string telefonodestinatario {
            get {
                return this.telefonodestinatarioField;
            }
            set {
                this.telefonodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string ciudaddestinatario {
            get {
                return this.ciudaddestinatarioField;
            }
            set {
                this.ciudaddestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string barriodestinatario {
            get {
                return this.barriodestinatarioField;
            }
            set {
                this.barriodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string totalpeso {
            get {
                return this.totalpesoField;
            }
            set {
                this.totalpesoField = value;
            }
        }
        
        /// <remarks/>
        public string totalpesovolumen {
            get {
                return this.totalpesovolumenField;
            }
            set {
                this.totalpesovolumenField = value;
            }
        }
        
        /// <remarks/>
        public string totalvalormercancia {
            get {
                return this.totalvalormercanciaField;
            }
            set {
                this.totalvalormercanciaField = value;
            }
        }
        
        /// <remarks/>
        public string formapago {
            get {
                return this.formapagoField;
            }
            set {
                this.formapagoField = value;
            }
        }
        
        /// <remarks/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string llevabodega {
            get {
                return this.llevabodegaField;
            }
            set {
                this.llevabodegaField = value;
            }
        }
        
        /// <remarks/>
        public string recogebodega {
            get {
                return this.recogebodegaField;
            }
            set {
                this.recogebodegaField = value;
            }
        }
        
        /// <remarks/>
        public string centrocostos {
            get {
                return this.centrocostosField;
            }
            set {
                this.centrocostosField = value;
            }
        }
        
        /// <remarks/>
        public string totalvalorproducto {
            get {
                return this.totalvalorproductoField;
            }
            set {
                this.totalvalorproductoField = value;
            }
        }
        
        /// <remarks/>
        public string tiposervicio {
            get {
                return this.tiposervicioField;
            }
            set {
                this.tiposervicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unidad")]
        public unidad[] unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentoreferencia", IsNullable=true)]
        public documentoreferencia[] documentoreferencia {
            get {
                return this.documentoreferenciaField;
            }
            set {
                this.documentoreferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numeroreferenciacliente {
            get {
                return this.numeroreferenciaclienteField;
            }
            set {
                this.numeroreferenciaclienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class recogida {
        
        private string numeroField;
        
        private string fechaField;
        
        private string ventanainicioField;
        
        private string ventanafinField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string ventanainicio {
            get {
                return this.ventanainicioField;
            }
            set {
                this.ventanainicioField = value;
            }
        }
        
        /// <remarks/>
        public string ventanafin {
            get {
                return this.ventanafinField;
            }
            set {
                this.ventanafinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpRespuesta {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string codigointernoField;
        
        private string mensajeinternoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string codigointerno {
            get {
                return this.codigointernoField;
            }
            set {
                this.codigointernoField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeinterno {
            get {
                return this.mensajeinternoField;
            }
            set {
                this.mensajeinternoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpSeguimiento {
        
        private string fechaseguimientoField;
        
        private string observacionesField;
        
        private string fechasolucionField;
        
        private string essolucionField;
        
        private string usuarioseguimientoField;
        
        private string funcionarioclienteField;
        
        private string funcionariotccField;
        
        private string nuevadireccionField;
        
        private string fechareofrecimientoField;
        
        private string ventanahorariaField;
        
        private string seguimientoField;
        
        /// <remarks/>
        public string fechaseguimiento {
            get {
                return this.fechaseguimientoField;
            }
            set {
                this.fechaseguimientoField = value;
            }
        }
        
        /// <remarks/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string fechasolucion {
            get {
                return this.fechasolucionField;
            }
            set {
                this.fechasolucionField = value;
            }
        }
        
        /// <remarks/>
        public string essolucion {
            get {
                return this.essolucionField;
            }
            set {
                this.essolucionField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioseguimiento {
            get {
                return this.usuarioseguimientoField;
            }
            set {
                this.usuarioseguimientoField = value;
            }
        }
        
        /// <remarks/>
        public string funcionariocliente {
            get {
                return this.funcionarioclienteField;
            }
            set {
                this.funcionarioclienteField = value;
            }
        }
        
        /// <remarks/>
        public string funcionariotcc {
            get {
                return this.funcionariotccField;
            }
            set {
                this.funcionariotccField = value;
            }
        }
        
        /// <remarks/>
        public string nuevadireccion {
            get {
                return this.nuevadireccionField;
            }
            set {
                this.nuevadireccionField = value;
            }
        }
        
        /// <remarks/>
        public string fechareofrecimiento {
            get {
                return this.fechareofrecimientoField;
            }
            set {
                this.fechareofrecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string ventanahoraria {
            get {
                return this.ventanahorariaField;
            }
            set {
                this.ventanahorariaField = value;
            }
        }
        
        /// <remarks/>
        public string seguimiento {
            get {
                return this.seguimientoField;
            }
            set {
                this.seguimientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpNovedad {
        
        private string codigoField;
        
        private tpCiudadBasico ciudadplanteaField;
        
        private tpCiudadBasico ciudadsolucionaField;
        
        private string fechanovedadField;
        
        private string fechaplanteamientoField;
        
        private string usuarioplanteaField;
        
        private string fechasolucionField;
        
        private string causaField;
        
        private string codigocausaField;
        
        private string estadoField;
        
        private string tipodenovedadField;
        
        private string comentariosField;
        
        private tpSeguimiento[] seguimientosField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public tpCiudadBasico ciudadplantea {
            get {
                return this.ciudadplanteaField;
            }
            set {
                this.ciudadplanteaField = value;
            }
        }
        
        /// <remarks/>
        public tpCiudadBasico ciudadsoluciona {
            get {
                return this.ciudadsolucionaField;
            }
            set {
                this.ciudadsolucionaField = value;
            }
        }
        
        /// <remarks/>
        public string fechanovedad {
            get {
                return this.fechanovedadField;
            }
            set {
                this.fechanovedadField = value;
            }
        }
        
        /// <remarks/>
        public string fechaplanteamiento {
            get {
                return this.fechaplanteamientoField;
            }
            set {
                this.fechaplanteamientoField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioplantea {
            get {
                return this.usuarioplanteaField;
            }
            set {
                this.usuarioplanteaField = value;
            }
        }
        
        /// <remarks/>
        public string fechasolucion {
            get {
                return this.fechasolucionField;
            }
            set {
                this.fechasolucionField = value;
            }
        }
        
        /// <remarks/>
        public string causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
            }
        }
        
        /// <remarks/>
        public string codigocausa {
            get {
                return this.codigocausaField;
            }
            set {
                this.codigocausaField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string tipodenovedad {
            get {
                return this.tipodenovedadField;
            }
            set {
                this.tipodenovedadField = value;
            }
        }
        
        /// <remarks/>
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("seguimiento", IsNullable=false)]
        public tpSeguimiento[] seguimientos {
            get {
                return this.seguimientosField;
            }
            set {
                this.seguimientosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpCiudadBasico {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        private string codigodaneField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
        
        /// <remarks/>
        public string codigodane {
            get {
                return this.codigodaneField;
            }
            set {
                this.codigodaneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpUnidadNegocioBasico {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpEstadoBasico {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpTipoDocumentoBasico {
        
        private string idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpDocumentoReferecia {
        
        private tpTipoDocumentoBasico tipodocumentoField;
        
        private string numerodocumentoField;
        
        private string fechadocumentoField;
        
        /// <remarks/>
        public tpTipoDocumentoBasico tipodocumento {
            get {
                return this.tipodocumentoField;
            }
            set {
                this.tipodocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string numerodocumento {
            get {
                return this.numerodocumentoField;
            }
            set {
                this.numerodocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string fechadocumento {
            get {
                return this.fechadocumentoField;
            }
            set {
                this.fechadocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd")]
    public partial class tpRemesas {
        
        private string idremesaField;
        
        private string numeroremesaField;
        
        private string fecharemesaField;
        
        private tpDocumentoReferecia[] documentosField;
        
        private tpCiudadBasico ciudadorigenField;
        
        private tpCiudadBasico ciudaddestinoField;
        
        private tpEstadoBasico estadoremesaField;
        
        private string tieneimagenField;
        
        private string tienenovedadField;
        
        private string nombreremitenteField;
        
        private string direccionremitenteField;
        
        private string telefonoremitenteField;
        
        private string tipoidentificacionremitenteField;
        
        private string identificacionremitenteField;
        
        private string cuentaremitenteField;
        
        private string nombrecuentaremitenteField;
        
        private string nombredestinatarioField;
        
        private string telefonodestinatarioField;
        
        private string direcciondestinatarioField;
        
        private string tipoidentificaciondestinatarioField;
        
        private string identificaciondestinatarioField;
        
        private string formapagoField;
        
        private string unidadesField;
        
        private string pesorealField;
        
        private string observacionesField;
        
        private string fechaentregaField;
        
        private string diasentregaField;
        
        private tpUnidadNegocioBasico unidadnegocioField;
        
        private string valormercanciaField;
        
        private string ceoporigenField;
        
        private string ceopdestinoField;
        
        private string fleteField;
        
        private string viajenacionalField;
        
        private string movilnacionalField;
        
        private string vannacionalField;
        
        private string viajelocalField;
        
        private string movillocalField;
        
        private string tokenField;
        
        private tpNovedad[] novedadesField;
        
        /// <remarks/>
        public string idremesa {
            get {
                return this.idremesaField;
            }
            set {
                this.idremesaField = value;
            }
        }
        
        /// <remarks/>
        public string numeroremesa {
            get {
                return this.numeroremesaField;
            }
            set {
                this.numeroremesaField = value;
            }
        }
        
        /// <remarks/>
        public string fecharemesa {
            get {
                return this.fecharemesaField;
            }
            set {
                this.fecharemesaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("documento", IsNullable=false)]
        public tpDocumentoReferecia[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        public tpCiudadBasico ciudadorigen {
            get {
                return this.ciudadorigenField;
            }
            set {
                this.ciudadorigenField = value;
            }
        }
        
        /// <remarks/>
        public tpCiudadBasico ciudaddestino {
            get {
                return this.ciudaddestinoField;
            }
            set {
                this.ciudaddestinoField = value;
            }
        }
        
        /// <remarks/>
        public tpEstadoBasico estadoremesa {
            get {
                return this.estadoremesaField;
            }
            set {
                this.estadoremesaField = value;
            }
        }
        
        /// <remarks/>
        public string tieneimagen {
            get {
                return this.tieneimagenField;
            }
            set {
                this.tieneimagenField = value;
            }
        }
        
        /// <remarks/>
        public string tienenovedad {
            get {
                return this.tienenovedadField;
            }
            set {
                this.tienenovedadField = value;
            }
        }
        
        /// <remarks/>
        public string nombreremitente {
            get {
                return this.nombreremitenteField;
            }
            set {
                this.nombreremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string direccionremitente {
            get {
                return this.direccionremitenteField;
            }
            set {
                this.direccionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string telefonoremitente {
            get {
                return this.telefonoremitenteField;
            }
            set {
                this.telefonoremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string tipoidentificacionremitente {
            get {
                return this.tipoidentificacionremitenteField;
            }
            set {
                this.tipoidentificacionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string identificacionremitente {
            get {
                return this.identificacionremitenteField;
            }
            set {
                this.identificacionremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string cuentaremitente {
            get {
                return this.cuentaremitenteField;
            }
            set {
                this.cuentaremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string nombrecuentaremitente {
            get {
                return this.nombrecuentaremitenteField;
            }
            set {
                this.nombrecuentaremitenteField = value;
            }
        }
        
        /// <remarks/>
        public string nombredestinatario {
            get {
                return this.nombredestinatarioField;
            }
            set {
                this.nombredestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string telefonodestinatario {
            get {
                return this.telefonodestinatarioField;
            }
            set {
                this.telefonodestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string direcciondestinatario {
            get {
                return this.direcciondestinatarioField;
            }
            set {
                this.direcciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string tipoidentificaciondestinatario {
            get {
                return this.tipoidentificaciondestinatarioField;
            }
            set {
                this.tipoidentificaciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string identificaciondestinatario {
            get {
                return this.identificaciondestinatarioField;
            }
            set {
                this.identificaciondestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string formapago {
            get {
                return this.formapagoField;
            }
            set {
                this.formapagoField = value;
            }
        }
        
        /// <remarks/>
        public string unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
        
        /// <remarks/>
        public string pesoreal {
            get {
                return this.pesorealField;
            }
            set {
                this.pesorealField = value;
            }
        }
        
        /// <remarks/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string fechaentrega {
            get {
                return this.fechaentregaField;
            }
            set {
                this.fechaentregaField = value;
            }
        }
        
        /// <remarks/>
        public string diasentrega {
            get {
                return this.diasentregaField;
            }
            set {
                this.diasentregaField = value;
            }
        }
        
        /// <remarks/>
        public tpUnidadNegocioBasico unidadnegocio {
            get {
                return this.unidadnegocioField;
            }
            set {
                this.unidadnegocioField = value;
            }
        }
        
        /// <remarks/>
        public string valormercancia {
            get {
                return this.valormercanciaField;
            }
            set {
                this.valormercanciaField = value;
            }
        }
        
        /// <remarks/>
        public string ceoporigen {
            get {
                return this.ceoporigenField;
            }
            set {
                this.ceoporigenField = value;
            }
        }
        
        /// <remarks/>
        public string ceopdestino {
            get {
                return this.ceopdestinoField;
            }
            set {
                this.ceopdestinoField = value;
            }
        }
        
        /// <remarks/>
        public string flete {
            get {
                return this.fleteField;
            }
            set {
                this.fleteField = value;
            }
        }
        
        /// <remarks/>
        public string viajenacional {
            get {
                return this.viajenacionalField;
            }
            set {
                this.viajenacionalField = value;
            }
        }
        
        /// <remarks/>
        public string movilnacional {
            get {
                return this.movilnacionalField;
            }
            set {
                this.movilnacionalField = value;
            }
        }
        
        /// <remarks/>
        public string vannacional {
            get {
                return this.vannacionalField;
            }
            set {
                this.vannacionalField = value;
            }
        }
        
        /// <remarks/>
        public string viajelocal {
            get {
                return this.viajelocalField;
            }
            set {
                this.viajelocalField = value;
            }
        }
        
        /// <remarks/>
        public string movillocal {
            get {
                return this.movillocalField;
            }
            set {
                this.movillocalField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("novedad", IsNullable=false)]
        public tpNovedad[] novedades {
            get {
                return this.novedadesField;
            }
            set {
                this.novedadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class documentoreferencia {
        
        private string tipodocumentoField;
        
        private string numerodocumentoField;
        
        private string fechadocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipodocumento {
            get {
                return this.tipodocumentoField;
            }
            set {
                this.tipodocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numerodocumento {
            get {
                return this.numerodocumentoField;
            }
            set {
                this.numerodocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechadocumento {
            get {
                return this.fechadocumentoField;
            }
            set {
                this.fechadocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class unidad {
        
        private string tipounidadField;
        
        private string tipoempaqueField;
        
        private string claseempaqueField;
        
        private string dicecontenerField;
        
        private string kilosrealesField;
        
        private string largoField;
        
        private string altoField;
        
        private string anchoField;
        
        private string pesovolumenField;
        
        private string valormercanciaField;
        
        private string codigobarrasField;
        
        private string numerobolsaField;
        
        private string referenciasField;
        
        private string unidadesinternasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipounidad {
            get {
                return this.tipounidadField;
            }
            set {
                this.tipounidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoempaque {
            get {
                return this.tipoempaqueField;
            }
            set {
                this.tipoempaqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claseempaque {
            get {
                return this.claseempaqueField;
            }
            set {
                this.claseempaqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dicecontener {
            get {
                return this.dicecontenerField;
            }
            set {
                this.dicecontenerField = value;
            }
        }
        
        /// <remarks/>
        public string kilosreales {
            get {
                return this.kilosrealesField;
            }
            set {
                this.kilosrealesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
            }
        }
        
        /// <remarks/>
        public string pesovolumen {
            get {
                return this.pesovolumenField;
            }
            set {
                this.pesovolumenField = value;
            }
        }
        
        /// <remarks/>
        public string valormercancia {
            get {
                return this.valormercanciaField;
            }
            set {
                this.valormercanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigobarras {
            get {
                return this.codigobarrasField;
            }
            set {
                this.codigobarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numerobolsa {
            get {
                return this.numerobolsaField;
            }
            set {
                this.numerobolsaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referencias {
            get {
                return this.referenciasField;
            }
            set {
                this.referenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unidadesinternas {
            get {
                return this.unidadesinternasField;
            }
            set {
                this.unidadesinternasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class grabardespacho7respuesta {
        
        private string remesaField;
        
        private string numerorecogidaField;
        
        private string urlrelacionenvioField;
        
        private string urlremesaField;
        
        private string urlrotulosField;
        
        private string respuestaField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string remesa {
            get {
                return this.remesaField;
            }
            set {
                this.remesaField = value;
            }
        }
        
        /// <remarks/>
        public string numerorecogida {
            get {
                return this.numerorecogidaField;
            }
            set {
                this.numerorecogidaField = value;
            }
        }
        
        /// <remarks/>
        public string urlrelacionenvio {
            get {
                return this.urlrelacionenvioField;
            }
            set {
                this.urlrelacionenvioField = value;
            }
        }
        
        /// <remarks/>
        public string urlremesa {
            get {
                return this.urlremesaField;
            }
            set {
                this.urlremesaField = value;
            }
        }
        
        /// <remarks/>
        public string urlrotulos {
            get {
                return this.urlrotulosField;
            }
            set {
                this.urlrotulosField = value;
            }
        }
        
        /// <remarks/>
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class anulardespacho {
        
        private string claveField;
        
        private string numeroremesaField;
        
        private string fechadespachoField;
        
        private string cuentaremitenteField;
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string numeroremesa {
            get {
                return this.numeroremesaField;
            }
            set {
                this.numeroremesaField = value;
            }
        }
        
        /// <remarks/>
        public string fechadespacho {
            get {
                return this.fechadespachoField;
            }
            set {
                this.fechadespachoField = value;
            }
        }
        
        /// <remarks/>
        public string cuentaremitente {
            get {
                return this.cuentaremitenteField;
            }
            set {
                this.cuentaremitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class anulardespachorespuesta {
        
        private string respuestaField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class consultartrazabilidadremesa {
        
        private string claveField;
        
        private tpListaRemesaRemesa[] remesasField;
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("remesa", IsNullable=false)]
        public tpListaRemesaRemesa[] remesas {
            get {
                return this.remesasField;
            }
            set {
                this.remesasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd/remesa/")]
    public partial class tpListaRemesaRemesa {
        
        private string numeroField;
        
        private string esrelacionField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string esrelacion {
            get {
                return this.esrelacionField;
            }
            set {
                this.esrelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tcc.com.co/xsd")]
    public partial class consultartrazabilidadremesarespuesta {
        
        private tpRemesas[] remesasField;
        
        private tpRespuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("remesa", IsNullable=false)]
        public tpRemesas[] remesas {
            get {
                return this.remesasField;
            }
            set {
                this.remesasField = value;
            }
        }
        
        /// <remarks/>
        public tpRespuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void grabardespacho7CompletedEventHandler(object sender, grabardespacho7CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class grabardespacho7CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal grabardespacho7CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public grabardespacho7respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((grabardespacho7respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void anulardespachoCompletedEventHandler(object sender, anulardespachoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class anulardespachoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal anulardespachoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anulardespachorespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anulardespachorespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultarinformacionremesaCompletedEventHandler(object sender, consultarinformacionremesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarinformacionremesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarinformacionremesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultartrazabilidadremesarespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultartrazabilidadremesarespuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591